package ml.socshared.adapter.vk.vkclient.domain;

public enum  ErrorCode {
    //VK CLIENT ERRORS
    INVALID_ARGUMENTS(-1),

    NOT_FOUND_CONSTANT_FOR_ERROR(0),

    //VK API ERRORS
    UNDEFINED_ERROR(1),
    APP_IS_OFF(2),
    UNDEFINED_CODE_VALUE(3),
    INVALID_SIGNATURE(4),
    ERROR_OF_AUTHORIZATION(5),
    MANY_REQUESTS(6),
    DONT_HAVE_PERMISSIONS(7),
    INVALID_REQUEST(8),
    MANY_SAME_TYPE_ACTIONS(9),
    INTERNAL_SERVER_ERROR(10),
    CAPTCHA(14),
    FORBIDDEN(15),
    MUST_HAVE_HTTPS(16),
    USER_VALIDATION_REQUIRED(17),
    PAGE_REMOVED_OR_BLOCKED(18),
    THIS_APP_NOT_STANDALONE(20),
    THIS_APP_NOT_STANDALONE_OR_OPENAPI(21),
    METHOD_IS_OFF(23),
    CONFIRMATION_REQUIRED(24),
    KEY_OF_GROUP_NOT_VALID(27),
    KEY_OF_APP_NOT_VALID(28),
    REACH_LIMIT(29),
    PROFILE_IS_PRIVATE(30),
    NOT_IMPLEMENTED_YET(33),
    INVALID_PARAMETERS_LIST(100),
    INVALID_API_ID(101),
    INVALID_ID_USER(113),
    INVALID_TIMESTAMP(150),
    ALBUM_ACCESS_FORBIDDEN(200),
    AUDIO_ACCESS_FORBIDDEN(201),
    GROUP_ACCESS_FORBIDDEN(202),
    ALBUM_OVERFLOW(300),
    ACTION_FORBIDDEN(500),
    NOT_PERMISSION_OF_ACTION_BY_ADVERTISING_ACCOUNT(600),
    ADVERTISING_ACCOUNT_ERROR(603),
    RECAPTCHA_NEEDED(3300),
    PHONE_VALIDATION_NEEDED(3301),
    PASSWORD_VALIDATION_NEEDED(3302),
    OTP_APP_VALIDATION_NEEDED(3303),
    EMAIL_CONFIRMATION_NEEDED(3304),
    ASSERT_VOTES(3305);

    ErrorCode(int code) {
        this.code = code;
    }
    public int getCode() {
        return code;
    }


    private int code;
}
