image: java:11

stages:
  - build-and-docker
  - docker-push
  - docker-deploy-swarm

before_script:
  - chmod +x gradlew

build-and-docker:
  stage: build-and-docker
  script:
    - ./gradlew clean build
    - docker 2>/dev/null 1>&2 rmi `docker images -aq` || true
    - docker build -t $CI_DOCKER_LOGIN/socshared-vk-adapter .

docker-push:
  stage: docker-push
  script:
    - docker login -u "$CI_DOCKER_LOGIN" -p "$CI_DOCKER_PASSWORD"
    - docker push $CI_DOCKER_LOGIN/socshared-vk-adapter

docker-deploy-swarm:
  stage: docker-deploy-swarm
  script:
    - touch .env_vk
    - echo "POSTGRES_USER=admin" >> .env_vk
    - echo "POSTGRES_PASS=admin" >> .env_vk
    - echo "POSTGRES_DB=vk" >> .env_vk
    - echo "POSTGRES_HOST=postgres-db" >> .env_vk
    - echo "SPRING_PROFILE=$SPRING_PROFILE" >> .env_vk
    - docker stack deploy -c docker-compose.yaml socshared
