image: java:11

stages:
  - build
  - docker-build
  - docker-push
  - docker-deploy-swarm

before_script:
  - chmod +x gradlew

build:
  stage: build
  script: ./gradlew clean build
  artifacts:
    paths:
      - build/libs/socshared-vk-adapter-1.0.0-SNAPSHOT.jar

docker-build:
  stage: docker-build
  script:
    - sudo docker build -t $CI_DOCKER_LOGIN/socshared-vk-adapter .

docker-push:
  stage: docker-push
  script:
    - sudo docker login -u "$CI_DOCKER_LOGIN" -p "$CI_DOCKER_PASSWORD"
    - sudo docker push $CI_DOCKER_LOGIN/socshared-vk-adapter

docker-deploy-swarm:
  stage: docker-deploy-swarm
  script:
    - touch .env_vk_pg
    - echo "POSTGRES_USER=admin" >>  .env_vk_pg
    - echo "POSTGRES_PASSWORD=admin" >>  .env_vk_pg
    - echo "POSTGRES_DB=vk" >> .env_vk_pg
    - touch .env_vk
    - echo "POSTGRES_USER=admin" >> .env_vk
    - echo "POSTGRES_PASS=admin" >> .env_vk
    - echo "POSTGRES_DB=vk" >> .env_vk
    - echo "POSTGRES_HOST=vk_postgres_db" >> .env_vk
    - sudo docker stack deploy -c docker-compose.yaml socshared
