version: '3.7'
services:

  vk_adapter:
    image: lexgv/socshared-vk-adapter
    ports:
      - 8082:8082
    env_file:
      - .env_vk

  vk_postgres_db:
    image: postgres:11
    deploy:
      replicas: 1
    ports:
      - 5433:5432
    env_file:
      - .env_vk_pg

networks:
  default:
    name: socshared