server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}/${POSTGRES_DB:vk}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
  jpa:
    generate-ddl: true
  zipkin:
    base-url: http://zipkin:9411/
    service:
      name: ${spring.application.name}

  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: auditevents, beans, caches, conditions, configprops, health, httptrace, info, loggers, metrics, mappings, shutdown

feign:
  url:
    auth: ${AUTH_SERVICE:http://auth-service:9999/}


logging:
  level:
    ml:
      socshared:
        adapter:
          vk:
            vkclient:
              VKClient: DEBUG
