server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}/${POSTGRES_DB:vk}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
  jpa:
    generate-ddl: true
  zipkin:
    base-url: http://zipkin:9411/
    service:
      name: "socshared-vk-adapter"
  main:
    allow-bean-definition-overriding: true
  

logging:
  level:
    ml:
      socshared:
        adapter:
          vk:
            vkclient:
              VKClient: DEBUG
